/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/salud": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Salud
         * @description Responde 503 si falla la base. MQTT y Telegram no marcan la API como caída: sin MQTT
         *     la API sigue sirviendo el historial y la ingesta reconecta sola.
         */
        get: operations["salud_api_v1_salud_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login
         * @description Abre una sesión y la entrega en la cookie `sesion`.
         */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Cierra la sesión actual y borra la cookie.
         */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/yo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Yo
         * @description El usuario de la sesión y sus casas, con su rol en cada una.
         */
        get: operations["yo_api_v1_auth_yo_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/cambiar-clave": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cambiar Clave
         * @description Cambia la clave y cierra las demás sesiones del usuario (§12.2).
         */
        post: operations["cambiar_clave_api_v1_auth_cambiar_clave_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sesiones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Sesiones
         * @description Las sesiones abiertas del usuario, de la más reciente a la más antigua.
         */
        get: operations["sesiones_api_v1_auth_sesiones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/sesiones/{sesion_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cerrar Sesion
         * @description Cierra una de las sesiones del usuario (por ejemplo, la de un celular perdido).
         */
        delete: operations["cerrar_sesion_api_v1_auth_sesiones__sesion_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description Las casas del usuario, con su conexión y cuántas alarmas tienen abiertas.
         */
        get: operations["listar_api_v1_casas_get"];
        put?: never;
        /**
         * Crear
         * @description Registra una casa. Su central necesita además un usuario MQTT (scripts/usuario_mqtt.sh).
         */
        post: operations["crear_api_v1_casas_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas/{casa_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver */
        get: operations["ver_api_v1_casas__casa_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Cambiar */
        patch: operations["cambiar_api_v1_casas__casa_id__patch"];
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/estado": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Estado
         * @description Lo mismo que envía el WebSocket. El frontend lo consulta cada 5 s si el WS falla (§9).
         */
        get: operations["estado_api_v1_casas__casa_id__estado_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/ajustes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver */
        get: operations["ver_api_v1_casas__casa_id__ajustes_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Cambiar
         * @description Cambia solo los campos enviados; un null se ignora.
         */
        patch: operations["cambiar_api_v1_casas__casa_id__ajustes_patch"];
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/comandos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ultimos
         * @description Los últimos comandos de la casa, del más reciente al más antiguo.
         */
        get: operations["ultimos_api_v1_casas__casa_id__comandos_get"];
        put?: never;
        /**
         * Enviar
         * @description Silencia, activa o desactiva un nodo. 409 si la central o el nodo no tienen conexión.
         */
        post: operations["enviar_api_v1_casas__casa_id__comandos_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/comandos/silenciar-todo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Silenciar Todo
         * @description Silencia todos los nodos con alarma. Solo exige que la central esté conectada.
         */
        post: operations["silenciar_todo_api_v1_casas__casa_id__comandos_silenciar_todo_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/comandos/{comando_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Ver */
        get: operations["ver_api_v1_casas__casa_id__comandos__comando_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/alarmas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description Paginado por cursor: para la página siguiente se pasa `antes_de_id = siguiente`.
         */
        get: operations["listar_api_v1_casas__casa_id__alarmas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/casas/{casa_id}/eventos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Listar
         * @description Paginado por cursor: para la página siguiente se pasa `antes_de_id = siguiente`.
         */
        get: operations["listar_api_v1_casas__casa_id__eventos_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Ajustes */
        Ajustes: {
            /** Recordatorio Min */
            recordatorio_min: number;
            /** Recordatorio Conexion Min */
            recordatorio_conexion_min: number;
            /** Minutos Central Caida */
            minutos_central_caida: number;
            /** Avisar Nodo Sin Conexion */
            avisar_nodo_sin_conexion: boolean;
            /** Avisar Resueltas */
            avisar_resueltas: boolean;
        };
        /** Alarma */
        Alarma: {
            /** Id */
            id: number;
            /** Nodo Id */
            nodo_id: number | null;
            /** Nodo Nombre */
            nodo_nombre: string;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "INTRUSION" | "SIN_MOVIMIENTO" | "AGUA" | "GAS" | "TEMPERATURA" | "NODO_SIN_CONEXION" | "CENTRAL_DESCONECTADA";
            /** Texto */
            texto: string;
            /**
             * Inicio En
             * Format: date-time
             */
            inicio_en: string;
            /** Fin En */
            fin_en: string | null;
            /** Duracion S */
            duracion_s: number;
            /** Valor */
            valor: number | null;
            /** Cerrada Por */
            cerrada_por: ("usuario" | "central" | "automatica") | null;
            cerrada_por_usuario: components["schemas"]["UsuarioBreve"] | null;
            /** Avisos Enviados */
            avisos_enviados: number;
        };
        /**
         * CambioAjustes
         * @description Solo cambian los campos que se envían.
         */
        CambioAjustes: {
            /** Recordatorio Min */
            recordatorio_min?: number | null;
            /** Recordatorio Conexion Min */
            recordatorio_conexion_min?: number | null;
            /** Minutos Central Caida */
            minutos_central_caida?: number | null;
            /** Avisar Nodo Sin Conexion */
            avisar_nodo_sin_conexion?: boolean | null;
            /** Avisar Resueltas */
            avisar_resueltas?: boolean | null;
        };
        /** CambioCasa */
        CambioCasa: {
            /** Nombre */
            nombre?: string | null;
        };
        /** CambioClave */
        CambioClave: {
            /** Clave Actual */
            clave_actual: string;
            /** Clave Nueva */
            clave_nueva: string;
        };
        /** Casa */
        Casa: {
            /** Id */
            id: number;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Creada En
             * Format: date-time
             */
            creada_en: string;
            ajustes: components["schemas"]["Ajustes"];
        };
        /** CasaDelUsuario */
        CasaDelUsuario: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /**
             * Rol
             * @enum {string}
             */
            rol: "admin" | "cuidador";
        };
        /** CasaNueva */
        CasaNueva: {
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
        };
        /** Comando */
        Comando: {
            /** Id */
            id: number;
            /** Nodo Id */
            nodo_id: number | null;
            /**
             * Accion
             * @enum {string}
             */
            accion: "activar" | "desactivar" | "silenciar";
            /** Sub */
            sub: number;
            /**
             * Estado
             * @enum {string}
             */
            estado: "pendiente" | "confirmado" | "sin_confirmar";
            /**
             * Creado En
             * Format: date-time
             */
            creado_en: string;
            /** Resuelto En */
            resuelto_en: string | null;
            usuario: components["schemas"]["UsuarioBreve"] | null;
        };
        /** ComandoNuevo */
        ComandoNuevo: {
            /** Nodo */
            nodo: number;
            /**
             * Accion
             * @enum {string}
             */
            accion: "activar" | "desactivar" | "silenciar";
            /**
             * Sub
             * @description 1 = presencia del nodo 4; solo para activar o desactivar
             * @default 0
             * @enum {integer}
             */
            sub: 0 | 1;
        };
        /** DetalleError */
        DetalleError: {
            /** Codigo */
            codigo: string;
            /** Mensaje */
            mensaje: string;
            /** Campos */
            campos?: string[] | null;
        };
        /**
         * Error
         * @description {"detail": {"codigo": ..., "mensaje": ...}}
         */
        Error: {
            detail: components["schemas"]["DetalleError"];
        };
        /** EstadoCasa */
        EstadoCasa: {
            /** Casa Id */
            casa_id: number;
            /** Online */
            online: boolean;
            /** Online Cambio En */
            online_cambio_en: string | null;
            /** Recibido En */
            recibido_en: string | null;
            /** Antiguedad S */
            antiguedad_s: number | null;
            central: components["schemas"]["EstadoCentral"] | null;
            /** Alarmas Abiertas */
            alarmas_abiertas: components["schemas"]["Alarma"][];
        };
        /**
         * EstadoCentral
         * @description El payload de casa/<ID>/estado (§4.3).
         */
        EstadoCentral: {
            /** Hora */
            hora: string;
            /** Horavalida */
            horaValida: boolean;
            /**
             * Red
             * @enum {string}
             */
            red: "wifi" | "ap";
            /** Nodos */
            nodos: components["schemas"]["NodoCentral"][];
            /** Eventos */
            eventos: components["schemas"]["EventoCentral"][];
        };
        /** Evento */
        Evento: {
            /** Id */
            id: number;
            /**
             * Ocurrido En
             * Format: date-time
             */
            ocurrido_en: string;
            /**
             * Origen
             * @enum {string}
             */
            origen: "central" | "backend" | "usuario";
            usuario: components["schemas"]["UsuarioBreve"] | null;
            /** Nodo Id */
            nodo_id: number | null;
            /**
             * Tipo
             * @enum {string}
             */
            tipo: "alarma" | "alarma_resuelta" | "comando" | "habilitado" | "conexion" | "central" | "info";
            /** Texto */
            texto: string;
            /** Es Alarma */
            es_alarma: boolean;
        };
        /**
         * EventoCentral
         * @description Una entrada de la bitácora de la central. No tiene id (§4.3).
         */
        EventoCentral: {
            /** T */
            t: string;
            /** X */
            x: string;
            /** A */
            a: boolean;
        };
        /** Login */
        Login: {
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Clave */
            clave: string;
        };
        /**
         * NodoCentral
         * @description Un nodo del payload de estado (§4.3). Los nombres del JSON se conservan en la API.
         */
        NodoCentral: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
            /** Visto */
            visto: boolean;
            /** Enlinea */
            enLinea: boolean;
            /** Hab */
            hab: number;
            /** Al */
            al: number;
            /** Mov */
            mov: number;
            /** Fl */
            fl: number;
            /** C1 */
            c1: number;
            /** L1 */
            l1: number;
            /** C2 */
            c2: number;
            /** L2 */
            l2: number;
            /** V1 */
            v1: number;
            /** V2 */
            v2: number;
            /** Hace */
            hace: number;
        };
        /** PaginaAlarmas */
        PaginaAlarmas: {
            /** Items */
            items: components["schemas"]["Alarma"][];
            /** Siguiente */
            siguiente: number | null;
        };
        /** PaginaEventos */
        PaginaEventos: {
            /** Items */
            items: components["schemas"]["Evento"][];
            /** Siguiente */
            siguiente: number | null;
        };
        /** ResumenCasa */
        ResumenCasa: {
            /** Id */
            id: number;
            /** Codigo */
            codigo: string;
            /** Nombre */
            nombre: string;
            /**
             * Rol
             * @enum {string}
             */
            rol: "admin" | "cuidador";
            /** Online */
            online: boolean;
            /** Alarmas Abiertas */
            alarmas_abiertas: number;
        };
        /** Salud */
        Salud: {
            /** Ok */
            ok: boolean;
            /**
             * Db
             * @enum {string}
             */
            db: "ok" | "error";
            /**
             * Mqtt
             * @enum {string}
             */
            mqtt: "conectado" | "desconectado";
            /**
             * Telegram
             * @enum {string}
             */
            telegram: "conectado" | "desactivado" | "error";
            /** Version */
            version: string;
        };
        /** SesionAbierta */
        SesionAbierta: {
            /** Id */
            id: number;
            /** User Agent */
            user_agent: string | null;
            /** Ip */
            ip: string | null;
            /**
             * Creada En
             * Format: date-time
             */
            creada_en: string;
            /**
             * Ultimo Uso En
             * Format: date-time
             */
            ultimo_uso_en: string;
            /**
             * Expira En
             * Format: date-time
             */
            expira_en: string;
            /** Actual */
            actual: boolean;
        };
        /** Usuario */
        Usuario: {
            /** Id */
            id: number;
            /** Email */
            email: string;
            /** Nombre */
            nombre: string;
            /** Es Superadmin */
            es_superadmin: boolean;
        };
        /**
         * UsuarioBreve
         * @description Quién hizo algo: silenció una alarma, envió un comando…
         */
        UsuarioBreve: {
            /** Id */
            id: number;
            /** Nombre */
            nombre: string;
        };
        /** Yo */
        Yo: {
            usuario: components["schemas"]["Usuario"];
            /** Casas */
            casas: components["schemas"]["CasaDelUsuario"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    salud_api_v1_salud_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
            /** @description La base de datos no responde */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Salud"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Login"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Usuario"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Demasiados intentos */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    yo_api_v1_auth_yo_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Yo"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cambiar_clave_api_v1_auth_cambiar_clave_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioClave"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    sesiones_api_v1_auth_sesiones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SesionAbierta"][];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cerrar_sesion_api_v1_auth_sesiones__sesion_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                sesion_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listar_api_v1_casas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResumenCasa"][];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    crear_api_v1_casas_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CasaNueva"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Casa"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ver_api_v1_casas__casa_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Casa"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cambiar_api_v1_casas__casa_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioCasa"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Casa"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    estado_api_v1_casas__casa_id__estado_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EstadoCasa"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ver_api_v1_casas__casa_id__ajustes_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ajustes"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    cambiar_api_v1_casas__casa_id__ajustes_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CambioAjustes"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Ajustes"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ultimos_api_v1_casas__casa_id__comandos_get: {
        parameters: {
            query?: {
                limit?: number;
            };
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comando"][];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    enviar_api_v1_casas__casa_id__comandos_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ComandoNuevo"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comando"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Demasiados intentos */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio no disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    silenciar_todo_api_v1_casas__casa_id__comandos_silenciar_todo_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comando"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Conflicto */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Demasiados intentos */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Servicio no disponible */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    ver_api_v1_casas__casa_id__comandos__comando_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                comando_id: number;
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comando"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listar_api_v1_casas__casa_id__alarmas_get: {
        parameters: {
            query?: {
                abiertas?: boolean | null;
                nodo?: number | null;
                tipo?: ("INTRUSION" | "SIN_MOVIMIENTO" | "AGUA" | "GAS" | "TEMPERATURA" | "NODO_SIN_CONEXION" | "CENTRAL_DESCONECTADA") | null;
                /** @description inicio_en ≥ desde */
                desde?: string | null;
                /** @description inicio_en < hasta */
                hasta?: string | null;
                limit?: number;
                /** @description el `siguiente` anterior */
                antes_de_id?: number | null;
            };
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaAlarmas"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
    listar_api_v1_casas__casa_id__eventos_get: {
        parameters: {
            query?: {
                /** @description ocurrido_en ≥ desde */
                desde?: string | null;
                /** @description ocurrido_en < hasta */
                hasta?: string | null;
                solo_alarmas?: boolean;
                limit?: number;
                /** @description el `siguiente` anterior */
                antes_de_id?: number | null;
            };
            header?: never;
            path: {
                casa_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginaEventos"];
                };
            };
            /** @description Solicitud inválida */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No autenticado */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Sin permiso u origen inválido */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description No encontrado */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
        };
    };
}
